@startuml entity diagram for "Álbum de Figurinhas Online"
' Entidades
entity User {
  + identity
  + displayName
  + email
  + dustBalance
  -- Methods --
  + addDust(amount: Integer)
  + subtractDust(amount: Integer)
  + updateProfile(displayName: String, email: String)
}

entity StickerPack {
  + identity
  + coverImage
  + containedStickers
  + stickerQuantity
  + stickerRaritiesOnly
  + uniqueStickerOnly
  + isPublished
  + dustCost
  + collectionId
  -- Methods --
  + publishPack()
  + deactivatePack()
  + addSticker(sticker: Sticker)
  + removeSticker(sticker: Sticker)
  + addCollectionStickes(collection: Collection)
  + changeDustCost(cost: Integer)
}

entity TransactionLog {
  + identity
  + userId
  + stickerId
  + stickerPackId
  + date
  + type
  -- Methods --
  + createLog(userId: String, type: String, stickerId: Integer, stickerPackId: Integer)
}

' Agregado: Colecao
package "Agregado: Colecao" {
  entity Collection {
    + identity
    + name
    + description
    + isPublished
    -- Methods --
    + publishCollection()
    + updateCollectionInfo(name: String, description: String)
    + addSticker(sticker: Sticker)
  }
  entity Sticker {
    + identity
    + image
    + name
    + description
    + rarity
    + collectionId
    -- Methods --
    + changeName(name: String)
    + changeDescription(description: String)
    + changeRarity(rarity: String)
    + changeImage(image: String)
    + deactivate()
    + publish()
  }
  Collection "1" -- "0..*" Sticker : contains >
  note right of Collection
    O agregado Colecao representa uma coleção de figurinhas,
    incluindo informações sobre a coleção e as figurinhas que ela contém.
    Este agregado é responsável por gerenciar o ciclo de vida da coleção
    e suas figurinhas, incluindo a adição de novas figurinhas e a publicação
    da coleção para os usuários.
  end note
}

' Domain Services
package "Domain Services" <<Rectangle>> {
  entity "TradeSystem" as TradeSystem {
    -- Methods --
    + buyStickerWithDust(userId: String, stickerId: String)
    + buyStickerPackWithDust(userId: String, packId: String)
    + convertStickersToDust(stickerIds: List)
    + openStickerPack(userId: String, packId: String)
    + logTransaction(userId: String, type: String, stickerId: String, packId: String)
  }
  entity "CollectionManagement" as CollectionManagement {
    -- Methods --
    + createCollection(name: String, description: String)
    + changeCollectionName(collectionId: String, name: String)
    + changeCollectionDescription(collectionId: String, description: String)
    + deactivateCollection(collectionId: String)
    + publishCollection(collectionId: String)
  }
  entity "StickerManagement" as StickerManagement {
    stickerList
    dustCostMultiplier
    -- Methods --
    + deleteSticker(stickerId: String)
  }
  entity "StickerPackManagement" as PackManagement {
    + stickerPackList
    + dustCostMultiplier
    -- Methods --
    + deleteStickerPack(stickerPackId: String)
    + changeDustCostMultiplier(multiplier: Integer)
    + findStickerPackByCollection(collectionId: String)
    + findStickerPackBySticker(stickerId: String)
  }
}

' Repositórios
entity TradeRepository {
  + saveTransactionLog
  -- Methods --
  + logTransaction(transaction: TransactionLog)

' Value Objects
class Rarity << (V,orchid) Value Object >> {
  + value
}

' Agregados e Relacionamentos
Collection "1" -- "0..*" Sticker : contains >
Collection "1..*" o-- "0..*" StickerPack : distributes >
StickerPack "1" *-- "0..*" Sticker : contains >
User "1" -- "0..*" Collection : owns >
User "1" -- "1" TradeSystem : interacts >
TradeSystem -- TradeRepository : uses >

' Notas explicativas
note right of StickerPack
  Cada pacote pode pertencer a uma ou mais coleções.
  Os pacotes podem ser configurados para não conter figurinhas repetidas.
  O administrador pode controlar a quantidade de figurinhas por pacote.
  O administrador pode definir a raridade das figurinhas em cada pacote.
end note

note left of Collection
  Uma coleção pode distribuir vários tipos de pacotes, incluindo pacotes promocionais com figurinhas de múltiplas coleções.
end note

note right of Sticker
  A raridade da figurinha é definida pelo administrador e influencia a probabilidade de ser encontrada em pacotes.
end note

note right of TradeSystem
  O Sistema de Trocas é um serviço de domínio que gerencia a compra, destruição e troca de figurinhas.
  Ele interage com o Repositório de Trocas para armazenar logs de cada transação para fins de auditoria.
  Agora também registra a abertura de pacotes de figurinhas pelos usuários.
end note

note right of TransactionLog
  Cada log de transação armazena detalhes sobre a troca realizada, incluindo o usuário, figurinha, data e tipo de transação.
  Agora também inclui logs de quando um usuário abre um pacote de figurinhas.
end note

note right of TradeRepository
  O Repositório de Trocas é responsável por persistir os logs de transação no sistema de armazenamento.
  Agora também armazena logs de abertura de pacotes.
end note

note right of CollectionManagement
  O serviço de Gestão de Coleções é responsável por administrar o ciclo de vida das coleções no sistema.
  Uma vez que a coleção é publicada, as figurinhas não podem ser alteradas ou removidas. Somente novas figurinhas podem ser adicionadas.
end note

note right of StickerManagement
  O serviço de Gestão de Figurinhas é responsável por administrar o ciclo de vida das figurinhas nas coleções.
end note

note right of StickerPackManagement
  O serviço de Gestão de Pacotes é responsável por administrar o ciclo de vida dos pacotes de figurinhas no sistema.
  Isso inclui a criação de novos pacotes, a atualização de seu conteúdo e a desativação de pacotes que não estão mais disponíveis.
  uma vez que um pacote é publicado, seu conteúdo não pode ser alterado.
end note

@enduml
